version: '3.9'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
     - "5672:5672"
     - "15672:15672"
  app-api:
    build: ./app-api
    ports:
      - "8080:8080"
    restart: always
  customer-facade:
    build: ./customer-facade
    ports:
      - "8088:8088"
    restart: always