services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
     - "5672:5672"
     - "15672:15672"
  app-api:
    build: 
      context: ./app-api
    ports:
      - "8080:8080"
    restart: always
  customer-facade:
    build:
      context: ./customer-facade
    ports:
      - "8088:8088"
    restart: always
    depends_on:
      - rabbitMq
  merchant-facade:
    build:
      context: ./merchant-facade
    ports:
      - "8089:8089"
    restart: always
    depends_on:
      - rabbitMq
  account-management:
    build:
      context: ./account-management
    restart: always
    depends_on:
     - rabbitMq
  payment-management:
    build:
      context: ./payment-management
    restart: always
    depends_on:
     - rabbitMq
  token-service:
    build:
      context: ./tokenservice
    restart: always
    depends_on:
     - rabbitMq
  repostservice:
    build:
      context: ./reportservice
    restart: always
    depends_on:
      - rabbitMq