services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
     - "5672:5672"
     - "15672:15672"
  app-api:
    build: ./app-api
    ports:
      - "8080:8080"
    restart: always
  customer-facade:
    build:
      context: .
      dockerfile: customer-facade/Dockerfile
    ports:
      - "8088:8088"
    restart: always
    depends_on:
      - rabbitMq
  merchant-facade:
    build:
      context: .
      dockerfile: merchant-facade/Dockerfile
    ports:
      - "8089:8089"
    restart: always
    depends_on:
      - rabbitMq
  account-management:
    build: ./account-management
    restart: always
    depends_on:
     - rabbitMq